Projectclient/Controllers/HangerController.cs
using Projectclient.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace Projectclient.Controllers
{
    public class HangerController : Controller
    {
        // GET: Hanger
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(AddHanger Ah, string HangerBtn)
        {
            if (HangerBtn == "AddHanger")
            {
                if (ModelState.IsValid)
                {
                    string st = "";
                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri("https://localhost:44334/api/");
                        var responseTask = client.PostAsJsonAsync<AddHanger>("HangerDetails", Ah);
                        responseTask.Wait();
                        var result = responseTask.Result;
                        var readData = result.Content.ReadAsAsync<string>();
                        if (result.IsSuccessStatusCode)
                        {
                            st = readData.Result;
                            ViewBag.msg = st;
                            ModelState.Clear();
                            return View(new AddHanger());
                        }
                        else
                        {
                            st = readData.Result;
                            ViewBag.msg = st;
                            return View();
                        }
                    }
                }
                else
                {
                    ViewBag.msg = "couldn't add Hanger";
                    return View();
                }
            }
            else if (HangerBtn == "Reset")
            {
                ModelState.Clear();
                return View();
            }
            else
            {
                return View();
            }
        }
    }
}

Projectclient/Controllers/LoginclientController.cs
using Projectclient.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Razor.Parser.SyntaxTree;
using System.Web.Security;

namespace Projectclient.Controllers
{
    public class LoginclientController : Controller
    {
        // GET: Loginclient
        public ActionResult Signup()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Loginxyz(string s)
        {
            TempData["Job"] = s;
            return View();
        }
        //public ActionResult logout()
        //{
        //    return View();
        //}
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Enter(Class1 c)
        {
            Loginentity l = null;
            string st = "";
            // HttpClient client = new HttpClient();
            // Class1 emps = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress=new Uri("https://localhost:44334/api/Project");
                var responseTask = client.PostAsJsonAsync<Class1>("Project", c);
                responseTask.Wait();
                var result = responseTask.Result;

                //client.BaseAddress=new Uri("https://localhost:44334/api/Project");
                //var responseTask = client.GetAsync("Project");
                //responseTask.Wait();
                //var result=responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readdata = result.Content.ReadAsAsync<Loginentity>();
                    readdata.Wait();
                    l=readdata.Result;

                    //var readdata = result.Content.ReadAsAsync<Class1>();
                    //readdata.Wait();
                    //emps=readdata.Result;
                    //if (st.Equals("1"))
                    //{
                    //    st="Invalid Credentials";
                    //    ViewBag.msg = st;
                    //}
                    //else
                    //{
                    //    FormsAuthentication.SetAuthCookie(st, false);
                    //    Session["type"]=st;
                    //    Session.Timeout=10;
                    //    //  object value = HttpContext.Session.SetString("type", st);

                    //    var x = Session["type"];
                    //    ViewBag.msg="Login Success";
                    //}

                    // result.Content.ReadAsStreamAsync<IList<EMP>>();



                    Session["type"]=l.type;
                    Session["email"]=l.email;
                    ViewBag.msg="Login Success";
                    return View("success");

                     

                }
                else
                {
                    var readdata = result.Content.ReadAsAsync<Loginentity>();
                    readdata.Wait();
                    l=readdata.Result;
                    ViewBag.msg="Invalid Credentials";
                    return View("Index");
                }
                //ModelState.AddModelError(string.Empty, "No emp found");
            }
        }
        //   ViewBag.msg=st;



        public ActionResult success()
        {
            return View();
        }

        public ActionResult Logout()
        {
            Session.Abandon();

            Session.Clear();


            Session.RemoveAll();
            System.Web.Security.FormsAuthentication.SignOut();
            Session["type"]=null;
            Session.Timeout=1;
            // return View();
            return RedirectToAction("Index");
        }


    }
    }


    

Projectclient/Views/Shared/_Admin.cshtml
@*@{
    bool isLoggedin = true;
    if (string.IsNullOrWhiteSpace(User.Identity.Name))
    {
        isLoggedin=false;
    }
}*@


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    @*@{
                        if (isLoggedin)
                        {
                            if (Session["type"].Equals("ADMIN"))
                            {
                                <li>@Html.ActionLink("CreateEmp", "Create", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Index", "Index", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Emp", "getEmlployees", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Logout", "Signout", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                            }
                            else
                            {
                                <li>@Html.ActionLink("CreateEmp", "Create", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Index", "Index", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Emp", "getEmlployees", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Logout", "Signout", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                            }
                        }
                        else
                        {
                            <li>@Html.ActionLink("Login", "Login", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                        }
                    }*@

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Projectclient/Views/Shared/_Layout - Copy (2).cshtml
@*@{
    bool isLoggedin = true;
    if (string.IsNullOrWhiteSpace(User.Identity.Name))
    {
        isLoggedin=false;
    }
}*@


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    @*@{
                        if (isLoggedin)
                        {
                            if (Session["type"].Equals("ADMIN"))
                            {
                                <li>@Html.ActionLink("CreateEmp", "Create", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Index", "Index", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Emp", "getEmlployees", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Logout", "Signout", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                            }
                            else
                            {
                                <li>@Html.ActionLink("CreateEmp", "Create", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Index", "Index", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Emp", "getEmlployees", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Logout", "Signout", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                            }
                        }
                        else
                        {
                            <li>@Html.ActionLink("Login", "Login", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                        }
                    }*@

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Projectclient/Views/Shared/_Layout.cshtml
@*@{
    bool isLoggedin = true;
    if (string.IsNullOrWhiteSpace(User.Identity.Name))
    {
        isLoggedin=false;
    }
}*@


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script>
        function PreventBack() {
            window.history.forward();
        }
        setTimeout("PreventBack()", 0);
        window.onunload = function () { null }
    </script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    @*@{
                        if (isLoggedin)
                        {
                            if (Session["type"].Equals("ADMIN"))
                            {
                                <li>@Html.ActionLink("CreateEmp", "Create", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Index", "Index", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Emp", "getEmlployees", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Logout", "Signout", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                            }
                            else
                            {
                                <li>@Html.ActionLink("CreateEmp", "Create", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Index", "Index", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Emp", "getEmlployees", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Logout", "Signout", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                            }
                        }
                        else
                        {
                            <li>@Html.ActionLink("Login", "Login", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                        }
                    }*@

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Projectclient/Views/Shared/_Manager.cshtml
@*@{
    bool isLoggedin = true;
    if (string.IsNullOrWhiteSpace(User.Identity.Name))
    {
        isLoggedin=false;
    }
}*@


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    @*@{
                        if (isLoggedin)
                        {
                            if (Session["type"].Equals("ADMIN"))
                            {
                                <li>@Html.ActionLink("CreateEmp", "Create", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Index", "Index", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Emp", "getEmlployees", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Logout", "Signout", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                            }
                            else
                            {
                                <li>@Html.ActionLink("CreateEmp", "Create", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Index", "Index", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Emp", "getEmlployees", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Logout", "Signout", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                            }
                        }
                        else
                        {
                            <li>@Html.ActionLink("Login", "Login", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                        }
                    }*@

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Projectclient/Views/Shared/_Master1.cshtml
@*@{
    bool isLoggedin = true;
    if (string.IsNullOrWhiteSpace(User.Identity.Name))
    {
        isLoggedin=false;
    }
}*@


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script>
        function PreventBack() {
            window.history.forward();
        }
        setTimeout("PreventBack()", 0);
        window.onunload = function () { null }
    </script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Add Planes", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Add Pilots", "Index", "Pilot", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Add HangerDetails", "Index", "Hanger", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Logout", "Logout", "Loginclient", new { area = "" }, new { @class = "nav-link" })</li>
                    <li></li>
                    @*<li>@Html.ActionLink(@Session["type"], "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>*@
                    @*<li class="nav-link">@Session["type"]</li>*@

                    <li class="nav-link">
                        <div class="detailsdiv">
                            <ul class="navbar-nav ms-auto">
                                <li class="nav-item">
                                    <span class="nav-link">@Session["email"]</span>
                                </li>
                                <li class="nav-item">
                                    <span class="nav-link">@Session["type"]</span>
                                </li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Projectclient/Views/Shared/_Master2.cshtml
@*@{
    bool isLoggedin = true;
    if (string.IsNullOrWhiteSpace(User.Identity.Name))
    {
        isLoggedin=false;
    }
}*@


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script>
        function PreventBack() {
            window.history.forward();
        }
        setTimeout("PreventBack()", 0);
        window.onunload = function () { null }
    </script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Alloting_Plane_into_Hanger", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Get_Hanger_Status", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Logout", "Logout", "Loginclient", new { area = "" }, new { @class = "nav-link" })</li>
                    @*<li class="nav-link">@Session["type"]</li>*@
                </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <span class="nav-link">@Session["email"]</span>
                    </li>
                    <li class="nav-item">
                        <span class="nav-link">@Session["type"]</span>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>